### ISSUE TITLE
request module error

### ISSUE THREAD

**Issue by jianshu93** [jean-pierreBoth/archaea#1]
Hi Jean,

I ran the new commit. The database is the same I ask you download. request genomes is the query_genome in the repo.

tohnsw -d ./database/ -n 200

and then

request -b ./ -r ~/app/archaea-new/query_genome/ -n 50

I have the following errors:

 ************** initializing logger *****************

decoding argument dir
decoding argument dir
will use dumped sketch size
will use dumped kmer size
nb neighbours you will need in hnsw requests 50
reloading database ids from : ./seqdict.json
process_dir processed nb sequences : 5653
[2021-10-04T18:14:31Z ERROR request] an error occurred  nb msg sent : 5653, nb msg received : 5939692

Should be in line 200-202.  It seems the handle sent and receiver is not the same in the end.

Thanks,

Jianshu

**Comment by jean-pierreBoth** [comment]
fixed
