### ISSUE TITLE
request parameter `--seq` has no effect

### ISSUE THREAD

**Issue by simone-pignotti** [jean-pierreBoth/archaea#2]
Hi,

Thanks for this great tool, I compiled everything successfully from commit [8f12bb1](https://github.com/jean-pierreBoth/archaea/commit/8f12bb18781e5ce452c247dbed3eb0b246f97e03) and tested the `request` command on a small dataset with good results, using your pre-built GTDB-based dataset as reference.

Since the dataset was a multifasta containing multiple MAGs and I wanted to use each contig as a separate query, I tried to use the `--seq` option, but it seems to have no effect on the output. Could you provide more details about the effects of that parameter?

Thank you very much!

**Comment by jean-pierreBoth** [comment]
In fact --seq to have needs a database built with this option. Then your request is matched against
split blocks in database. With a database in one block, it has effectively no effect.

**Comment by simone-pignotti** [comment]
Thanks for the clarification! I am closing the issue but I suggest adding this info to the help message and/or the readme
