### ISSUE TITLE
GSearch gitter channel is live!

### ISSUE THREAD

**Issue by jianshu93** [jean-pierreBoth/archaea#7]
https://matrix.to/#/#gsearch-channel:gitter.im

Please joint this channel for gsearch user discussion, including bug report, feature request et.a.l

**Comment by jean-pierreBoth** [comment]
Hi jianshu,

I dowloaded Element on my phone, and created an account.
I do not find any room called gsearch. What did i miss?

Le mer. 24 juil. 2024 à 07:54, Jianshu_Zhao ***@***.***> a
écrit :

**Comment by jianshu93** [comment]
Hi jean,

I have no problem with it. You can just continue in your browser, no need to install the app or something. I suggest you GitHub account to create the gitter count.

Jianshu
